---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - collectd_packages_base
    - collectd_packages

- name: Make sure /etc/collectd and /etc/collectd/collectd.conf.d exists
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'
  with_items:
    - '/etc/collectd'
    - '/etc/collectd/collectd.conf.d'

- name: Install config file
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  with_items:
    - 'etc/collectd/collectd.conf'
  notify: [ 'Restart collectd' ]
