---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - collectd_packages_base
    - collectd_packages

- name: Make sure /etc/collectd and /etc/collectd/collectd.conf.d exists
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'
  with_items:
    - '/etc/collectd'
    - '/etc/collectd/collectd.conf.d'

- name: Check what plugins should be enabled
  script: script/detect_services.sh 
  register: collectd_register_detected_services_raw
  when: collectd_plugin_autodetect is defined and collectd_plugin_autodetect
  changed_when: False

- name: Extract list of plugins
  set_fact:
    collectd_register_detected_services: '{{ collectd_register_detected_services_raw.stdout_lines }}'
  when: collectd_plugin_autodetect is defined and collectd_plugin_autodetect

- name: Install config file
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  with_items:
    - 'etc/collectd/collectd.conf'
  notify: [ 'Restart collectd' ]
